#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout
blocked:
    path: /blocked
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: login/blocked.html.twig